FROM golang:1.15.3-alpine3.12 as builder
COPY . /src
WORKDIR /src
ENV GOOS=linux
ENV GOARCH=arm
RUN go build

FROM arm32v6/alpine
COPY --from=builder /src/releasebot /app/
RUN chmod +x /app/releasebot
WORKDIR /app
ENTRYPOINT [/app/releasebot]