FROM golang:alpine as builder
COPY . /src
WORKDIR /src
ENV GOOS=linux
ENV GOARCH=arm
ENV CGO_ENABLED=0
RUN go build

FROM arm32v7/alpine
COPY --from=builder /src/releasebot /app/
WORKDIR /app
ENTRYPOINT ["/app/releasebot"]