FROM golang:1.15.3-alpine3.12 as builder
COPY . /src
WORKDIR /src
ENV GOOS=linux
ENV GOARCH=arm
RUN go build

FROM arm32v7/ubuntu
COPY --from=builder /src/releasebot /app/
WORKDIR /app
ENTRYPOINT [/app/releasebot]